/**
 * Shortn API
 * API for shortening URLs and retrieving all shortened URLs.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';



import { Configuration }                                     from '../configuration';



export interface BlowupServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Blow up a shortened URL
     * 
     * @param _short The short part of the URL
     */
    shortGet(_short: string, extraHttpRequestParams?: any): Observable<{}>;

}
