/**
 * Shortn API
 * API for shortening URLs and retrieving all shortened URLs.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ShortClickCount } from '../model/models';
import { ShortURL } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface DasherServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Retrieve all shortened URLs
     * 
     */
    dasherShortAllGet(extraHttpRequestParams?: any): Observable<Array<ShortURL>>;

    /**
     * Get details for a Short
     * 
     * @param _short The short part of the URL
     */
    dasherShortShortClicksGet(_short: string, extraHttpRequestParams?: any): Observable<Array<ShortClickCount>>;

    /**
     * Delete a shortened URL
     * 
     * @param _short The short part of the URL
     */
    dasherShortShortDelete(_short: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Get details for a Short
     * 
     * @param _short The short part of the URL
     */
    dasherShortShortGet(_short: string, extraHttpRequestParams?: any): Observable<ShortURL>;

}
