volumes:
  node_modules:
services:
  frontend-container:
    image: mcr.microsoft.com/devcontainers/typescript-node:1-20
    volumes:
      - ../:/workspace:cached
      - node_modules:/workspace/src/services/front/node_modules
    command: sleep infinity
    environment:
      - GO111MODULE=on
    working_dir: /workspace
    depends_on:
      - mongodb
      - redis
  shortn:
    image: ghcr.io/menschomat/bly.li/shortn:main
    depends_on:
      - mongodb
      - redis
      - zookeeper
    #image: mensch0mat/bly.li.shortn:main
    environment:
      - OIDC_URL=${OIDC_URL}
      - OIDC_CLIENT_ID=${OIDC_CLIENT_ID}
      - TZ=${TZ}
    restart: unless-stopped

  dasher:
    image: ghcr.io/menschomat/bly.li/dasher:main
    depends_on:
      - mongodb
      - redis
    #image: mensch0mat/bly.li.shortn:main
    environment:
      - OIDC_URL=${OIDC_URL}
      - OIDC_CLIENT_ID=${OIDC_CLIENT_ID}
      - TZ=${TZ}
    restart: unless-stopped
  perso:
    image: ghcr.io/menschomat/bly.li/perso:main
    depends_on:
      - mongodb
      - redis
    #image: mensch0mat/bly.li.shortn:main
    environment:
      - TZ=${TZ}
    restart: unless-stopped
  blowup:
    image: ghcr.io/menschomat/bly.li/blowup:main
    depends_on:
      - mongodb
      - redis
    #image: mensch0mat/bly.li.blowup:main
    environment:
      - TZ=${TZ}
    restart: unless-stopped
  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    depends_on:
      - frontend-container
      - shortn
      - dasher
      - blowup
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: unless-stopped
    
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    restart: unless-stopped
    volumes:
      - ./frontend/prometheus.yml:/etc/prometheus/prometheus.yml:ro
