volumes:
  node_modules:
services:
  frontend-container:
    image: mcr.microsoft.com/devcontainers/typescript-node:1-20
    volumes:
      - ../:/workspace:cached
      - node_modules:/workspace/src/services/front/node_modules
    command: sleep infinity
    environment:
      - GO111MODULE=on
    working_dir: /workspace
    depends_on:
      - mongodb
      - redis
  shortn:
    build:
      context: ../src/.
      dockerfile: Dockerfile
      args:
        - SERVICE=shortn
    #image: mensch0mat/bly.li.shortn:main
    environment:
      - OIDC_URL=${OIDC_URL}
      - OIDC_CLIENT_ID=${OIDC_CLIENT_ID}
      - TZ=${TZ}
    restart: unless-stopped
  dasher:
    build:
      context: ../src/.
      dockerfile: Dockerfile
      args:
        - SERVICE=dasher
    #image: mensch0mat/bly.li.shortn:main
    environment:
      - OIDC_URL=${OIDC_URL}
      - OIDC_CLIENT_ID=${OIDC_CLIENT_ID}
      - TZ=${TZ}
    restart: unless-stopped
  perso:
    build:
      context: ../src/.
      dockerfile: Dockerfile
      args:
        - SERVICE=perso
    #image: mensch0mat/bly.li.shortn:main
    environment:
      - TZ=${TZ}
    restart: unless-stopped
  blowup:
    build:
      context: ../src/.
      dockerfile: Dockerfile
      args:
        - SERVICE=blowup
    #image: mensch0mat/bly.li.blowup:main
    environment:
      - TZ=${TZ}
    restart: unless-stopped
  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    depends_on:
      - frontend-container
      - shortn
      - dasher
      - blowup
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
