version: "3.8"
services:
  reverse-proxy:
    image: traefik:v2.10
    environment:
      - TZ=CET
    command:
      - --api
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
    labels:
      - "traefik.enable=true"
      - "traefik.port=80"
      - "traefik.http.routers.api.rule=Host(`traefik.localhost`)"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.api.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.users=traefik:$$2y$$05$$0o2x40VTfE3kHlqVDtk8AOuQQUZXRHTWz9yfq907708wESsdBjBMS"
      # ForwardAuth Middleware Configuration
      - "traefik.http.middlewares.auth-forward.forwardauth.address=http://traefik-forward-auth:4181" # ForwardAuth to traefik-forward-auth service
      - "traefik.http.middlewares.auth-forward.forwardauth.authResponseHeaders=X-Forwarded-User,X-Forwarded-Email"
      - "traefik.http.middlewares.auth-forward.forwardauth.trustForwardHeader=true"
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  traefik-forward-auth:
    image: thomseddon/traefik-forward-auth:latest
    environment:
      - TZ=CET
      - DEFAULT_PROVIDER=oidc
      - PROVIDERS_OIDC_ISSUER_URL=https://auth.base.menscho.space/realms/menscho.space
      - PROVIDERS_OIDC_USER_URL=https://auth.base.menscho.space/realms/master/protocol/openid-connect/userinfo
      - PROVIDERS_OIDC_CLIENT_ID=bly_li
      - PROVIDERS_OIDC_CLIENT_SECRET=<SECRETE_TO_CHANGE>
      - SECRET=squishy-<SECRETE_TO_CHANGE>
      - COOKIE_DOMAINS=blyli.localhost
      - INSECURE_COOKIE=true # Only for testing; use secure cookies in production
      - AUTH_HOST=auth.blyli.localhost
      - URL_PATH=/_oauth
      - LOG_LEVEL=debug
      - USER_ID_PATH=username
      - LIFETIME=3600 # Token lifetime in seconds
      #- COOKIE_SECURE=false # Set to false if not using HTTPS
      - LOGOUT_REDIRECT=https://auth.base.menscho.space/realms/menscho.space/protocol/openid-connect/logout?post_logout_redirect_uri=http://blyli.localhost/shortn&client_id=bly_li
      - PROVIDERS_OIDC_SCOPES=email,profile # Adjust scopes as needed
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik-forward-auth.rule=Host(`auth.blyli.localhost`)"
      #- "traefik.http.routers.traefik-forward-auth.rule=Host(`auth.base.menscho.space`)"
      - "traefik.http.services.traefik-forward-auth.loadbalancer.server.port=4181"
      - "traefik.http.routers.traefik-forward-auth.middlewares=auth-forward"

  shortn:
    build:
      context: src/.
      dockerfile: Shortn.Dockerfile
    #image: mensch0mat/bly.li.shortn:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.shortn.loadbalancer.server.port=8080"
      - "traefik.http.routers.shortn.rule=Host(`blyli.localhost`) && PathPrefix(`/shortn`) || PathPrefix(`/`)"
      - "traefik.http.routers.shortn.middlewares=shortn-rewrite,auth-forward"
      - "traefik.http.middlewares.shortn-rewrite.stripprefix.prefixes=/shortn"

  blowup:
    build:
      context: src/.
      dockerfile: Blowup.Dockerfile
    #image: mensch0mat/bly.li.blowup:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.blowup.loadbalancer.server.port=8080"
      - "traefik.http.routers.blowup.rule=Host(`blyli.localhost`)"
  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - redis_data:/data
volumes:
  redis_data:
    driver: local
