version: '3.8'
services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/go:1
    volumes:
      - ../../:/workspace:cached
    command: sleep infinity
    environment:
      - GO111MODULE=on
    working_dir: /workspace
    depends_on:
      - mongodb
      - redis
    #ports:
    #  - "3000:3000" # Example port if your app needs it
    # Do NOT specify 'command' here to avoid overriding the default shell

  mongodb:
    image: mongo:5.0
    container_name: dev_mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  redis:
    image: redis:latest
    container_name: dev_redis
    ports:
      - "6379:6379"
