services:
  backend-container:
    image: mcr.microsoft.com/devcontainers/go:1
    volumes:
      - ../../:/workspace:cached
    command: sleep infinity
    environment:
      - GO111MODULE=on
    working_dir: /workspace
    depends_on:
      - mongodb
      - redis
      - nginx
  front:
    build:
      context: ../../src/services/front/.
      dockerfile: Dockerfile
    image: mensch0mat/bly.li.front:main
    volumes:
      - ${CONFIG_PATH}:/usr/share/nginx/html/assets/config.json
    environment:
      - TZ=${TZ}
    networks:
      - blyli
    restart: unless-stopped