global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "perso-service"
    static_configs:
      - targets: ["host.docker.internal:9084"] # Change to your app's host:port
  - job_name: "shortn-service"
    static_configs:
      - targets: ["host.docker.internal:9082"] # Change to your app's host:port
  - job_name: "dasher-service"
    static_configs:
      - targets: ["host.docker.internal:9083"] # Change to your app's host:port
  - job_name: "blowup-service"
    static_configs:
      - targets: ["host.docker.internal:9081"] # Change to your app's host:port
