global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "perso-service"
    static_configs:
      - targets: ["host.docker.internal:2115"] # Change to your app's host:port
  - job_name: "blowup-service"
    static_configs:
      - targets: ["host.docker.internal:2114"] # Change to your app's host:port
