/**
 * Shortn API
 * API for shortening URLs and retrieving all shortened URLs.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ShortURL { 
    /**
     * The short-path of the URL
     */
    Short?: string;
    /**
     * The original URL
     */
    URL?: string;
    /**
     * The owner of the item
     */
    Owner?: string | null;
}

