version: "3.8"
services:
  mongodb:
    image: mongo:7
    ports:
      - "27017:27017"
    environment:
      - TZ=${TZ}
    restart: unless-stopped

  redis:
    image: redis/redis-stack:latest
    environment:
      - TZ=${TZ}
    ports:
      - "6379:6379"
      - "8001:8001"

  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes # Enables anonymous access (optional, for testing/dev)
    ports:
      - "2181:2181" # Client connections
    #volumes:
    #  - zookeeper_data:/bitnami/zookeeper  # Persistent storage
    restart: unless-stopped
