version: "3.8"
services:
  mongodb:
    image: mongo:7
    ports:
      - "127.0.0.1:27017:27017"
    environment:
      - TZ=${TZ}
    restart: unless-stopped

  redis:
    image: redis/redis-stack:latest
    environment:
      - TZ=${TZ}
    ports:
      - "127.0.0.1:6379:6379"
      - "127.0.0.1:8001:8001"

  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes # Enables anonymous access (optional, for testing/dev)
    ports:
      - "127.0.0.1:2181:2181"
    #volumes:
    #  - zookeeper_data:/bitnami/zookeeper  # Persistent storage
    restart: unless-stopped

  loki:
    image: grafana/loki:latest
    ports:
      - "127.0.0.1:3100:3100"
    command: -log.level=warn -config.file=/etc/loki/local-config.yaml
  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning