openapi: 3.0.0
info:
  title: Dasher API
  version: 1.0.0
  description: API for Statistics-Dashboards etc.

servers:
  - url: http://blyli.localhost
  - url: https://bly.li

tags:
  - name: dasher
    description: Endpoints for retrieving shortened URLs and statistics.
paths:
  /short/all:
    get:
      tags:
        - dasher
      summary: Retrieve all shortened URLs
      responses:
        "200":
          description: A list of shortened URLs
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "./shared.openapi.yml#/components/schemas/ShortURL"
        "500":
          description: Server error

  /short/{short}:
    delete:
      tags:
        - dasher
      summary: Delete a shortened URL
      parameters:
        - in: path
          name: short
          required: true
          schema:
            type: string
          description: The short part of the URL
      responses:
        "200":
          description: Deleted successfully
        "404":
          description: Short URL not found
