openapi: 3.0.0
info:
  title: Shortn API
  version: 1.0.0
  description: API for shortening URLs and retrieving all shortened URLs.

servers:
  - url: http://blyli.localhost/shortn
  - url: https://bly.li/shortn

tags:
  - name: shortn
    description: Endpoints for shortening URLs and retrieving all shortened URLs.

paths:
  /store:
    post:
      tags:
        - shortn
      summary: Shorten a URL
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "./shared.openapi.yml#/components/schemas/ShortnReq"
      responses:
        "200":
          description: Successfully shortened URL
          content:
            application/json:
              schema:
                $ref: "./shared.openapi.yml#/components/schemas/ShortURL"
        "400":
          description: Invalid input
