name: golang-pipeline

on:
  push:
    branches:
      - main
    tags:
      - "*"

env:
  REGISTRY: ghcr.io
  GITHUB_REPOSITORY: ${{ github.repository }} # e.g. "owner/repo"

jobs:
  extract_version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version_step.outputs.version }}
      version_tag: ${{ steps.version_step.outputs.version_tag }}
      latest_tag: ${{ steps.version_step.outputs.latest_tag }}
    steps:
      - name: Extract Version
        id: version_step
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
            echo "version=${VERSION}"           >> $GITHUB_OUTPUT
            echo "version_tag=${VERSION}"       >> $GITHUB_OUTPUT
            echo "latest_tag=latest"            >> $GITHUB_OUTPUT
          elif [[ "${GITHUB_REF}" == refs/heads/main ]]; then
            echo "version=main"                 >> $GITHUB_OUTPUT
            echo "version_tag=main"             >> $GITHUB_OUTPUT
          fi

      - name: Print Version
        run: |
          echo "version_tag=${{ steps.version_step.outputs.version_tag }}"
          echo "latest_tag= ${{ steps.version_step.outputs.latest_tag }}"

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Secret Scanning
        uses: trufflesecurity/trufflehog@main
        with:
          extra_args: --results=verified,unknown
  setup_docker:
    runs-on: ubuntu-latest
    needs: extract_version
    outputs:
      version: ${{ needs.extract_version.outputs.version }}
      version_tag: ${{ needs.extract_version.outputs.version_tag }}
      latest_tag: ${{ needs.extract_version.outputs.latest_tag }}
    steps:
      - name: Read version+latest-tag into ENV
        run: |
          echo "VERSION=${{ needs.extract_version.outputs.version }}"         >> $GITHUB_ENV
          echo "VERSION_TAG=${{ needs.extract_version.outputs.version_tag }}" >> $GITHUB_ENV
          if [ -n "${{ needs.extract_version.outputs.latest_tag }}" ]; then
            echo "LATEST_TAG=${{ needs.extract_version.outputs.latest_tag }}" >> $GITHUB_ENV
          fi

  build_and_push_frontend:
    runs-on: ubuntu-latest
    needs: setup_docker
    steps:
      - name: Compute lowercase repo name
        run: |
          echo "GITHUB_REPOSITORY_LC=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV
        env:
          GITHUB_REPOSITORY: ${{ env.GITHUB_REPOSITORY }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push frontend
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:src/services/front/."
          file: Dockerfile
          push: true
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            ${{ env.REGISTRY }}/${{ env.GITHUB_REPOSITORY_LC }}/front:${{ needs.setup_docker.outputs.version_tag }}
            ${{ env.LATEST_TAG && '${{ env.REGISTRY }}/${{ env.GITHUB_REPOSITORY_LC }}/front:latest' || '' }}
          build-args: |
            VERSION=${{ needs.setup_docker.outputs.version }}
            SERVICE=front

  build_and_push_backend:
    runs-on: ubuntu-latest
    needs: setup_docker
    strategy:
      matrix:
        service: [blowup, shortn, dasher, perso]
    steps:
      - name: Compute lowercase repo name
        run: |
          echo "GITHUB_REPOSITORY_LC=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV
        env:
          GITHUB_REPOSITORY: ${{ env.GITHUB_REPOSITORY }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push ${{ matrix.service }}
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:src/."
          file: Dockerfile
          push: true
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            ${{ env.REGISTRY }}/${{ env.GITHUB_REPOSITORY_LC }}/${{ matrix.service }}:${{ needs.setup_docker.outputs.version_tag }}
            ${{ env.LATEST_TAG && '${{ env.REGISTRY }}/${{ env.GITHUB_REPOSITORY_LC }}/${{ matrix.service }}:latest' || '' }}
          build-args: |
            VERSION=${{ needs.setup_docker.outputs.version }}
            SERVICE=${{ matrix.service }}
