name: golang-pipeline

on: 
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  extract_version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version_step.outputs.version }}
      version_tag: ${{ steps.version_step.outputs.version_tag }}
      latest_tag: ${{ steps.version_step.outputs.latest_tag }}
    steps:
      - name: Extract Version
        id: version_step
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
            echo "version=${VERSION}" >> $GITHUB_OUTPUT
            echo "version_tag=${VERSION}" >> $GITHUB_OUTPUT
            echo "latest_tag=latest" >> $GITHUB_OUTPUT
          elif [[ "${GITHUB_REF}" == refs/heads/main ]]; then
            echo "version=main" >> $GITHUB_OUTPUT
            echo "version_tag=main" >> $GITHUB_OUTPUT
          fi
      - name: Print Version
        run: |
          echo ${{ steps.version_step.outputs.version_tag }}
          echo ${{ steps.version_step.outputs.latest_tag }}

  setup_docker:
    runs-on: ubuntu-latest
    needs: extract_version
    outputs:
      version: ${{ needs.extract_version.outputs.version }}
      version_tag: ${{ needs.extract_version.outputs.version_tag }}
      latest_tag: ${{ needs.extract_version.outputs.latest_tag }}
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Prepare Docker Image Identifiers
        id: read-docker-image-identifiers
        run: |
          echo "VERSION_TAG=$(echo ${{ needs.extract_version.outputs.version_tag }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
          if [ -n "${{ needs.extract_version.outputs.latest_tag }}" ]; then
            echo "LATEST_TAG=$(echo ${{ needs.extract_version.outputs.latest_tag }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
          fi

  build_and_push_blowup:
    runs-on: ubuntu-latest
    needs: setup_docker
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB }}

      - name: Build and push BlowUp
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:src/."
          file: "Dockerfile"
          push: true
          tags: |
            mensch0mat/bly.li.blowup:${{ needs.setup_docker.outputs.version_tag }}
            ${{ env.LATEST_TAG && 'mensch0mat/bly.li.blowup:latest' || '' }}
          build-args: |
            VERSION=${{ needs.setup_docker.outputs.version }}
            SERVICE=blowup

  build_and_push_shortn:
    runs-on: ubuntu-latest
    needs: setup_docker
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB }}

      - name: Build and push Shortn
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:src/."
          file: "Dockerfile"
          push: true
          tags: |
            mensch0mat/bly.li.shortn:${{ needs.setup_docker.outputs.version_tag }}
            ${{ env.LATEST_TAG && 'mensch0mat/bly.li.shortn:latest' || '' }}
          build-args: |
            VERSION=${{ needs.setup_docker.outputs.version }}
            SERVICE=shortn

